packageExtensions:
  destack@*:
    peerDependencies:
      '@types/node': lts
      styled-components: lts
      typescript: lts
  react-hot-toast@*:
    peerDependencies:
      csstype: lts

packageExtensions:
  destack@*:
    peerDependencies:
      "@types/node": lts
      styled-components: lts
      typescript: lts
  react-hot-toast@*:
    peerDependencies:
      csstype: lts

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
