import Loading from "@/components/Loading";
import useTimeout from "@/lib/hooks/useTimeout";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import TimeoutRefreshesModal from "@/components/TimeoutRefreshesModal";

export default function Index() {
  const supabase = useSupabaseClient();
  const { timeout, error } = useTimeout(30000);
  const router = useRouter();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const handleLoad = async () => {
      const {
        data: { session },
        error,
      } = await supabase.auth.getSession();
      if (session) await router.push("/dashboard");
      if (session === null && !error) await router.push("/landing");
      setLoading(false);
    };
    handleLoad();
  }, [router, supabase.auth]);

  return (
    <>
      <Head>
        <title>Restaurant To Table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {loading ? <Loading screen /> : null}

        {/* TODO: MAKE THIS TIMEOUT PROMPT, BUT GET MENUS MODAL WORKING AGAIN FIRST BECAUSE IT IS BASICALLY THE SAME CONCEPT */}
        {timeout ? (
          <TimeoutRefreshesModal totalRetries={3} timeoutLength={30000} />
        ) : null}
        {/* TODO: ERROR HANDLING */}
        {error ? (
          <div>
            <h1>
              Error Loading Session! Let&apos;s figure out how to take care of
              this with Sentry!
            </h1>
            {console.error(error)}
          </div>
        ) : null}
      </main>
    </>
  );
}
